# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxTestDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'RxSwift', '~> 5'
pod 'RxCocoa', '~> 5'
  # Pods for RxTestDemo

  target 'RxTestDemoTests' do
    inherit! :search_paths
    # Pods for testing
pod 'RxBlocking', '~> 5'
pod 'RxTest', '~> 5'
  end

  target 'RxTestDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
